### ISSUE TITLE
Slider with different values using HTML/CSS

### ISSUE THREAD

**Issue by TheDemantor** [zero-to-mastery/webblocks-2022#138]

**Comment by sophiabrandt** [comment]
Can you elaborate on this issue?

**Comment by TheDemantor** [comment]
Sliders allow users to view and select a value from the range along a bar. They’re ideal for adjusting settings such as volume and brightness, or for applying image filters.

**Comment by TheDemantor** [comment]
Can I please work on that ?

**Comment by auxfuse** [comment]
You can. But please don't open Issues for things of this nature. You can build it following along to the contributors guide and submit a PR for review. 😄 🤜 
Have fun!
https://github.com/zero-to-mastery/webblocks-2022#%EF%B8%8F-how-to-contribute

We are going to close this Issue out and look forward to seeing your PR. 🎉
