### ISSUE TITLE
Adding BMI Calculator

### ISSUE THREAD

**Issue by Simranjain06** [zero-to-mastery/webblocks-2022#259]
I want to add BMI Calculator which is a Body mass Index calculator which takes input as your weight and height and tells your body mass index to check your health.

**Comment by Simranjain06** [comment]
Hey, I want to work on this can you assign me this task.

**Comment by sophiabrandt** [comment]
There is no need to open issues to add webblocks. If you want to contribute, please follow the guidelines in the README.

I will close this issue for now.
