### ISSUE TITLE
Add box-shadow

### ISSUE THREAD

**Issue by radhika141** [zero-to-mastery/webblocks-2022#262]
assign me this

**Comment by sophiabrandt** [comment]
I have no idea what "Add box-shadow" is supposed to do. Can you provide some context on what you want to do?

You can follow the guide in the [README](https://github.com/zero-to-mastery/webblocks-2022#%EF%B8%8F-how-to-contribute) to see how to contribute your component.

**Comment by coderboy-yash** [comment]
Hey I know how to add a box shadow on hovering the image.
Please  assign me this issue .
I can fix in just some odd hours.

**Comment by sophiabrandt** [comment]
On hovering what image?
If you want to make a contribution, please make a pull request.
It is not really clear to me what you want to do, but as long as it fits the criteria for this repo, feel free to make a PR.

**Comment by S44WN** [comment]
hey, I think it already has the box shadow on hovering.

Have a look at the encircled blocked that I hovered upon - 

<br>

![Screenshot (10)](https://user-images.githubusercontent.com/58899511/197577985-29e8e3ba-606d-4433-b979-f2f883442fd7.png)

<br>

moreover here's the code in - [webblocks-2022/src/style.css](https://github.com/zero-to-mastery/webblocks-2022/blob/master/src/styles.css)

<br>

take a look at the screenshot I took - 

<br>


![Screenshot (11)](https://user-images.githubusercontent.com/58899511/197578724-419c6c8b-d3bd-444c-9bb0-b8d6d6a4ec54.png)

**Comment by S44WN** [comment]
this issue can be closed I guess

**Comment by sophiabrandt** [comment]
I will close this for now.
Thanks @S44WN for providing some context as I wasn't sure what @radhika141 wanted to achieve by opening this issue.

@radhika141 if you still want to contribute, take a look at the README or discuss this in the discord server in the hacktoberfest-related channel.
