### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by michaella23** [zero-to-mastery/webblocks-2022#27]
![Screen Shot 2022-10-01 at 1 35 53 PM](https://user-images.githubusercontent.com/89760083/193423522-62fe8019-fc1a-4dab-8d3e-2ddf209309bb.png)
I don't know if it is required, but I saw on the Hacktoberfest site that maintainers should add a CONTRIBUTING file as well as a Code of Conduct. 🙂

**Comment by 0xSooki** [comment]
Haii, I would love to do it

**Comment by sophiabrandt** [comment]
The Contributors.md file is a recipe for a lot of merge conflicts.
I strongly advise against that, as it will stop from making this repo easily maintainable and goes as against the efforts in setting up the repo.

I have no problems with adding a code of conduct. But I don't know if it's necessary.
Please check the official ZTM Code of Conduct for reference .

**Comment by 0xSooki** [comment]
Would the same go for the CONTRIBUTING.md file? As it would only contain the guidelines of how to contribute to this project

**Comment by sophiabrandt** [comment]
@0xSooki no, I see no problem with that. Feel free to make a pull request. Please reference this issue, so we can close this issue after your PR was merged.
