### ISSUE TITLE
Improve Login page

### ISSUE THREAD

**Issue by AdiDub** [zero-to-mastery/webblocks-2022#399]
## Context
I would someone to create a new login page with better animation

## Prerequisites
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected result
A better login page with more CSS and styling

## Current result
[What is the current behavior?]

**Comment by AnishInamdar** [comment]
I would like to work on this issue. Can I start working on it ?
