### ISSUE TITLE
Add a Code Of Conduct File

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [zero-to-mastery/webblocks-2022#69]
Code of Conduct file is a very important aspect of an open source project.

May I add it @sirnotes?

**Comment by sirnotes** [comment]
I think that should be fine. Please submit a PR referencing this issue and we can review it.

**Comment by MrKrishnaAgarwal** [comment]
> I think that should be fine. Please submit a PR referencing this issue and we can review it.

Sure, I'll do that soon

**Comment by sky-akash05** [comment]
hi, I will love to contribute to your project . Will feel grateful i you can assign this to me,i have sound knowledge of CSS
