### ISSUE TITLE
Adding Light and Dark mode

### ISSUE THREAD

**Issue by lordashuchauhan** [zero-to-mastery/webblocks-2022#95]
Using a toggle button to switch between dark and light mode.

**Comment by lordashuchauhan** [comment]
@sirnotes please assign me this under hacktoberfest 2022.

**Comment by auxfuse** [comment]
@lordashuchauhan follow along to the contributors guide to submit this in a PR.

Make this a custom component to the Webblocks project, inside a directory named after yourself. Do not amend any of the base project files.

https://github.com/zero-to-mastery/webblocks-2022#%EF%B8%8F-how-to-contribute

Have fun! 🎈
